name: Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.147.8'
          extended: true

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: 全局安装 Dart Sass（npm 版）
        run: npm install -g sass

      - name: Build
        run: hugo --gc --minify

      - name: Deploy to gh-pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          # 如果是私有仓库，需设置 deploy_key 或 personal_token
